<?php

/**
 * Nigerian places
 *
 * @author   Kingsley Ochu <ochu.kc@gmail.com>
 * @version  1.0.0
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Credits: https://donjajo.com/ngstateslga-nigerian-36-states-local-government-areas-php-class/
 */
global $places;

$places['NG'] = array(
	'AB' => array(
			'Umuneochi'
		),
	'AD' => array(
			
			'Yola South'
		),
	'AK' => array(
			'Uyo'
		),
	'AN' => array(
			'Oyi'
		),
	'BA' => array(
			'Zaki' 
		),
	'BY' => array(
			'Yenegoa'
		),
	'BE' => array(
			'Vandeikya'
		),
	'BO' => array(
			'Abadam',
			'Askira/Uba',
			'Bama',
			'Bayo',
			'Biu',
			'Chibok',
			'Damboa',
			'Dikwa',
			'Gubio',
			'Guzamala',
			'Gwoza',
			'Hawul',
			'Jere',
			'Kaga',
			'Kala/Balge',
			'Konduga',
			'Kukawa',
			'Kwaya Kusar',
			'Mafa',
			'Magumeri',
			'Maiduguri',
			'Marte',
			'Mobbar',
			'Monguno',
			'Ngala',
			'Nganzai',
			'Shani' 
		),
	'CR' => array(
			'Akpabuyo',
			'Odukpani',
			'Akamkpa',
			'Biase',
			'Abi',
			'Ikom',
			'Yarkur',
			'Odubra',
			'Boki',
			'Ogoja',
			'Yala',
			'Obanliku',
			'Obudu',
			'Calabar South',
			'Etung',
			'Bekwara',
			'Bakassi',
			'Calabar Municipality'
		),
	'DE' => array(
			'Oshimili',
			'Aniocha',
			'Aniocha South',
			'Ika South',
			'Ika North-East',
			'Ndokwa West',
			'Ndokwa East',
			'Isoko south',
			'Isoko North',
			'Bomadi',
			'Burutu',
			'Ughelli South',
			'Ughelli North',
			'Ethiope West',
			'Ethiope East',
			'Sapele',
			'Okpe',
			'Warri North',
			'Warri South',
			'Uvwie',
			'Udu',
			'Warri Central',
			'Ukwani',
			'Oshimili North',
			'Patani'
		),
	'EB' => array(
			'Afikpo South',
			'Afikpo North',
			'Onicha',
			'Ohaozara',
			'Abakaliki',
			'Ishielu',
			'lkwo',
			'Ezza',
			'Ezza South',
			'Ohaukwu',
			'Ebonyi',
			'Ivo' 
		),
	'ED'  => array(
			'Esan North-East',
			'Esan Central',
			'Esan West',
			'Egor',
			'Ukpoba',
			'Central',
			'Etsako Central',
			'Igueben',
			'Oredo',
			'Ovia SouthWest',
			'Ovia South-East',
			'Orhionwon',
			'Uhunmwonde',
			'Etsako East',
			'Esan South-East'
		),
	'EK' => array(
			'Ado',
			'Ekiti-East',
			'Ekiti-West', 
			'Emure/Ise/Orun',
			'Ekiti South-West',
			'Ikare',
			'Irepodun',
			'Ijero', 
			'Ido/Osi',
			'Oye',
			'Ikole',
			'Moba',
			'Gbonyin',
			'Efon',
			'Ise/Orun', 
			'Ilejemeje'
		),
	'EN' => array(
			'Enugu South', 
			'Igbo-Eze South',
			'Enugu North',
			'Nkanu',
			'Udi Agwu',
			'Oji-River',
			'Ezeagu',
			'IgboEze North',
			'Isi-Uzo',
			'Nsukka',
			'Igbo-Ekiti',
			'Uzo-Uwani',
			'Enugu East',
			'Aninri',
			'Nkanu East',
			'Udenu' 
		),
	'GO' => array(
			'Yamaltu/Delta'
		),
	'IM' => array(
			'Owerri West' 
		),
	'JI' => array(
			'Yankwashi' 
		),
	'KD' => array(
			'Birni-Gwari',
			'Chikun',
			'Giwa',
			'Igabi',
			'Ikara',
			'jaba',
			'Jema\'a',
			'Kachia',
			'Kaduna North',
			'Kaduna South',
			'Kagarko',
			'Kajuru',
			'Kaura',
			'Kauru',
			'Kubau',
			'Kudan',
			'Lere',
			'Makarfi',
			'Sabon-Gari',
			'Sanga',
			'Soba',
			'Zango-Kataf',
			'Zaria'
		),
	'KN' => array(
			'Ajingi',
			'Albasu',
			'Bagwai',
			'Bebeji',
			'Bichi',
			'Bunkure',
			'Dala',
			'Dambatta',
			'Dawakin Kudu',
			'Dawakin Tofa',
			'Doguwa',
			'Fagge',
			'Gabasawa',
			'Garko',
			'Garum',
			'Mallam',
			'Gaya',
			'Gezawa',
			'Gwale',
			'Gwarzo',
			'Kabo',
			'Kano Municipal',
			'Karaye',
			'Kibiya',
			'Kiru',
			'kumbotso',
			'Kunchi',
			'Kura',
			'Madobi',
			'Makoda',
			'Minjibir',
			'Nasarawa',
			'Rano',
			'Rimin Gado',
			'Rogo',
			'Shanono',
			'Sumaila',
			'Takali',
			'Tarauni',
			'Tofa',
			'Tsanyawa',
			'Tudun Wada',
			'Ungogo',
			'Warawa',
			'Wudil'
		),
	'KT' => array(
			'Bakori',
			'Batagarawa',
			'Batsari',
			'Baure',
			'Bindawa',
			'Charanchi',
			'Dandume',
			'Danja',
			'Dan Musa',
			'Daura',
			'Dutsi',
			'Dutsin-Ma',
			'Faskari',
			'Funtua',
			'Ingawa',
			'Jibia',
			'Kafur',
			'Kaita',
			'Kankara',
			'Kankia',
			'Katsina',
			'Kurfi',
			'Kusada',
			'Mai\'Adua',
			'Malumfashi',
			'Mani',
			'Mashi',
			'Matazuu',
			'Musawa',
			'Rimi',
			'Sabuwa',
			'Safana',
			'Sandamu',
			'Zango' 
		),
	'KW' => array(
			'Aleiro',
			'Arewa-Dandi',
			'Argungu',
			'Augie',
			'Bagudo',
			'Birnin Kebbi',
			'Bunza',
			'Dandi', 
			'Fakai',
			'Gwandu',
			'Jega',
			'Kalgo', 
			'Koko/Besse',
			'Maiyama',
			'Ngaski',
			'Sakaba',
			'Shanga',
			'Suru',
			'Wasagu/Danko',
			'Yauri',
			'Zuru' 
		),
	'KO' => array(
			'Adavi',
			'Ajaokuta',
			'Ankpa',
			'Bassa',
			'Dekina',
			'Ibaji',
			'Idah',
			'Igalamela-Odolu',
			'Ijumu',
			'Kabba/Bunu',
			'Kogi',
			'Lokoja',
			'Mopa-Muro',
			'Ofu',
			'Ogori/Mangongo',
			'Okehi',
			'Okene',
			'Olamabolo',
			'Omala',
			'Yagba East',
			'Yagba West'
		),
	'KW' => array(
			'Asa',
			'Baruten',
			'Edu',
			'Ekiti',
			'Ifelodun',
			'Ilorin East',
			'Ilorin West',
			'Irepodun',
			'Isin',
			'Kaiama',
			'Moro',
			'Offa',
			'Oke-Ero',
			'Oyun',
			'Pategi'
		),
	'LA' => array(
			'Agege',
			'Ajeromi-Ifelodun',
			'Alimosho',
			'Amuwo-Odofin',
			'Apapa',
			'Badagry',
			'Epe',
			'Eti-Osa',
			'Ibeju/Lekki',
			'Ifako-Ijaye',
			'Ikeja',
			'Ikorodu',
			'Kosofe',
			'Lagos Island',
			'Lagos Mainland',
			'Ikota',
			'Ikoyi',
			'Ajah',
			'Mushin',
			'Ojo',
			'Oshodi-Isolo',
			'Shomolu',
			'Surulere'
		),
	'NA' => array(
			'Akwanga',
			'Awe',
			'Doma',
			'Karu',
			'Keana',
			'Keffi',
			'Kokona',
			'Lafia',
			'Nasarawa',
			'Nasarawa-Eggon',
			'Obi',
			'Toto',
			'Wamba' 
		),
	'NI' => array(
			'Agaie',
			'Agwara',
			'Bida',
			'Borgu',
			'Bosso',
			'Chanchaga',
			'Edati',
			'Gbako',
			'Gurara',
			'Katcha',
			'Kontagora', 
			'Lapai',
			'Lavun',
			'Magama',
			'Mariga',
			'Mashegu',
			'Mokwa',
			'Muya',
			'Pailoro',
			'Rafi',
			'Rijau',
			'Shiroro',
			'Suleja',
			'Tafa',
			'Wushishi'
		),
	'OG'  => array(
			'Abeokuta North',
			'Abeokuta South',
			'Ado-Odo/Ota',
			'Egbado North',
			'Egbado South',
			'Ewekoro',
			'Ifo',
			'Ijebu East',
			'Ijebu North',
			'Ijebu North East',
			'Ijebu Ode',
			'Ikenne',
			'Imeko-Afon',
			'Ipokia',
			'Obafemi-Owode',
			'Ogun Waterside',
			'Odeda',
			'Odogbolu',
			'Remo North',
			'Shagamu'
		),
	'ON' => array(
			'Akoko North East',
			'Akoko North West',
			'Akoko South Akure East',
			'Akoko South West',
			'Akure North',
			'Akure South',
			'Ese-Odo',
			'Idanre',
			'Ifedore',
			'Ilaje',
			'Ile-Oluji',
			'Okeigbo',
			'Irele',
			'Odigbo',
			'Okitipupa',
			'Ondo East',
			'Ondo West',
			'Ose',
			'Owo'
		),
	'OS' => array(
			'Aiyedade',
			'Aiyedire',
			'Atakumosa East',
			'Atakumosa West',
			'Boluwaduro',
			'Boripe',
			'Ede North',
			'Ede South',
			'Egbedore',
			'Ejigbo',
			'Ife Central',
			'Ife East',
			'Ife North',
			'Ife South',
			'Ifedayo',
			'Ifelodun',
			'Ila',
			'Ilesha East',
			'Ilesha West',
			'Irepodun',
			'Irewole',
			'Isokan',
			'Iwo',
			'Obokun',
			'Odo-Otin',
			'Ola-Oluwa',
			'Olorunda',
			'Oriade',
			'Orolu',
			'Osogbo'
		),
	'OY' => array(
			'Afijio',
			'Akinyele',
			'Atiba',
			'Atigbo',
			'Egbeda',
			'Ibadan Central',
			'Ibadan North',
			'Ibadan North West',
			'Ibadan South East',
			'Ibadan South West',
			'Ibarapa Central',
			'Ibarapa East',
			'Ibarapa North',
			'Ido',
			'Irepo',
			'Iseyin',
			'Itesiwaju',
			'Iwajowa',
			'Kajola',
			'Lagelu Ogbomosho North',
			'Ogbmosho South',
			'Ogo Oluwa',
			'Olorunsogo',
			'Oluyole',
			'Ona-Ara',
			'Orelope',
			'Ori Ire',
			'Oyo East',
			'Oyo West',
			'Saki East',
			'Saki West',
			'Surulere'
		),
	'PL' => array(
			'Barikin Ladi',
			'Bassa',
			'Bokkos',
			'Jos East',
			'Jos North',
			'Jos South',
			'Kanam',
			'Kanke',
			'Langtang North',
			'Langtang South',
			'Mangu',
			'Mikang',
			'Pankshin',
			'Qua\'an Pan',
			'Riyom',
			'Shendam',
			'Wase'
		),
	'RI' => array(
			'Abua/Odual',
			'Ahoada East',
			'Ahoada West',
			'Akuku Toru',
			'Andoni',
			'Asari-Toru',
			'Bonny',
			'Degema',
			'Emohua',
			'Eleme',
			'Etche',
			'Gokana',
			'Ikwerre',
			'Khana',
			'Obia/Akpor',
			'Ogba/Egbema/Ndoni',
			'Ogu/Bolo',
			'Okrika',
			'Omumma',
			'Opobo/Nkoro',
			'Oyigbo',
			'Port-Harcourt',
			'Tai' 
		),
	'SK' => array(
			'Binji',
			'Bodinga',
			'Dange-shnsi',
			'Gada',
			'Goronyo',
			'Gudu',
			'Gawabawa',
			'Illela',
			'Isa',
			'Kware',
			'kebbe',
			'Rabah',
			'Sabon birni',
			'Shagari',
			'Silame',
			'Sokoto North',
			'Sokoto South',
			'Tambuwal',
			'Tqngaza',
			'Tureta',
			'Wamako',
			'Wurno',
			'Yabo'
		),
	'TA' => array(
			'Ardo-kola',
			'Bali',
			'Donga',
			'Gashaka',
			'Cassol',
			'Ibi',
			'Jalingo',
			'Karin-Lamido',
			'Kurmi',
			'Lau',
			'Sardauna',
			'Takum',
			'Ussa',
			'Wukari',
			'Yorro',
			'Zing'
		),
	'YO' => array(
			'Bade',
			'Bursari',
			'Damaturu',
			'Fika',
			'Fune',
			'Geidam',
			'Gujba',
			'Gulani',
			'Jakusko',
			'Karasuwa',
			'Karawa',
			'Machina',
			'Nangere',
			'Nguru Potiskum',
			'Tarmua',
			'Yunusari',
			'Yusufari'
		),
	'ZA' => array(
			'Anka',
			'Bakura',
			'Birnin Magaji',
			'Bukkuyum',
			'Bungudu',
			'Gummi',
			'Gusau',
			'Kaura',
			'Namoda',
			'Maradun',
			'Maru',
			'Shinkafi',
			'Talata Mafara',
			'Tsafe',
			'Zurmi' 
		),
	'FC' => array(
			'Gwagwalada',
			'Kuje',
			'Abaji',
			'Abuja Municipal',
			'Bwari',
			'Kwali'	
		)
	);
